# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment and startup programs

export PATH=$PATH:$HOME/bin:/usr/java/default/bin
export JAVA_HOME=/usr/java/default
